# Generated by Django 3.2.25 on 2024-12-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='last_Name',
            new_name='last_name',
        ),
    ]
